{
 "cells": [
  {
   "cell_type": "raw",
   "id": "7e3ddc9e-335c-458b-9380-9d4e0bd4cda9",
   "metadata": {},
   "source": [
    "Q1/ What is exception in python? Write the difference between exception and syntax errors.\n",
    "Answer:-\n",
    "when a Python script encounters a situation that it cannot cope with, it raises an exception or  an exception is a Python object that represents an error.\n",
    "\n",
    "\n",
    "An Exception is an event that occurs during the program execution and disrupts the normal flow of the program's execution and errors mostly happen at compile-time.\n",
    "\n",
    "An error is an issue in a program that prevents the program from completing its task where  an exception is a condition that interrupts the normal flow of the program.\n",
    "\n",
    "Q2/ What happens when an exception is not handled?Explain with example.\n",
    "Answer:-\n",
    "If the exception is not handled by an except clause, the exception is re-raised after the finally clause has been executed.\n",
    "\n",
    "# initialize the amount variable\n",
    "age = 100\n",
    "\n",
    "# check that You are eligible to do that or not\n",
    "\n",
    "if(agg > 18)\n",
    "print(\"You are eligible to purchase book\")\n",
    "\n",
    "Q3/ Which python statement are used to catch and handle exception ?Explain with an example.\n",
    "Answer:-\n",
    "The try and except block in Python is used to catch and handle exceptions.\n",
    "If an exception occurs during execution of the try clause, the exception may be handled by an except clause.\n",
    "\n",
    "\n",
    "def divide(x, y):\n",
    "\ttry:\n",
    "\t\t\n",
    "\t\tresult = x / y\n",
    "\t\tprint(\"Yeah ! Your answer is :\", result)\n",
    "\texcept ZeroDivisionError:\n",
    "\t\tprint(\"Sorry ! You are dividing by zero \")\n",
    "\n",
    "divide(0, 30)\n",
    "output//\n",
    "Yeah ! Your answer is : 0.0\n",
    "\n",
    "Q4/  Explain with example  \n",
    "Try and else\n",
    "Finally\n",
    "raise\n",
    "Answer:-\n",
    "Try and else\n",
    "\tThe try block lets you test a block of code for errors. The except block lets you handle the error. The else block lets you execute code when there is no error.\n",
    "\n",
    "\n",
    "\n",
    "def divide(x, y):\n",
    "\ttry:\n",
    "\n",
    "\t\tresult = x / y\n",
    "\texcept ZeroDivisionError:\n",
    "\t\tprint(\"Sorry ! You are dividing by zero \")\n",
    "\telse:\n",
    "\t\tprint(\"Yeah ! Your answer is :\", result)\n",
    "\n",
    "\n",
    "divide(3, 2)\n",
    "divide(3, 0)\n",
    "\n",
    "finally\n",
    "The finally keyword is used in try... except blocks. It defines a block of code to run when the try... except...else block is final. The finally block will be executed no matter if the try block raises an error or not.\n",
    "\n",
    " \n",
    "def divide(x, y):\n",
    "\ttry:\n",
    "\t\t\n",
    "\t\tresult = x / y\n",
    "\texcept ZeroDivisionError:\n",
    "\t\tprint(\"Sorry ! You are dividing by zero \")\n",
    "\telse:\n",
    "\t\tprint(\"Yeah ! Your answer is :\", result)\n",
    "\tfinally:\n",
    "\t\t\n",
    "\t\tprint('This is always executed')\n",
    "\n",
    "\n",
    "divide(3, 2)\n",
    "divide(3, 0)\n",
    "\n",
    "Raise\n",
    "The raise keyword is used to raise an exception. You can define what kind of error to raise, and the text to print to the user.\n",
    "\n",
    "class validage(Exception):\n",
    "    def __init__(self,msg):\n",
    "        self.msg=msg\n",
    "def validage(age):\n",
    "    if age<0:\n",
    "        raise validage (\"Entered age is not velid\")\n",
    "    elif age >200:\n",
    "        raise validage (\"entered age is more high\")\n",
    "    else:\n",
    "        print(\" age is valid\")\n",
    "\n",
    "Q4/ What is custom exception in python? Explain why do we need custom exception ?Explain with an example.\n",
    "Answer:-\n",
    "\n",
    "Custom exceptions provide you the flexibility to add attributes and methods that are not part of a standard python exception. These can store additional information, like an application-specific error code, or provide utility methods that can be used to handle or present the exception to a user.\n",
    "custom exceptions help users when the code follows the it's easier to ask for forgiveness than permission coding strategy.\n",
    "\n",
    "\n",
    "\n",
    "class validage(Exception):\n",
    "    def __init__(self,msg):\n",
    "        self.msg=msg\n",
    "def validage(age):\n",
    "    if age<0:\n",
    "        raise validage (\"Entered age is not velid\")\n",
    "    elif age >200:\n",
    "        raise validage (\"entered age is more high\")\n",
    "    else:\n",
    "        print(\" age is valid\")\n",
    "try:\n",
    "    age =int (input(\"enter your age \"))\n",
    "    validage(age)\n",
    "except validage as e:\n",
    "    print (e)\n",
    "Q6/  Create a custom exception class and use this class to handle this exception.\n",
    "Answer:-\n",
    "class validage(Exception):\n",
    "    def __init__(self,msg):\n",
    "        self.msg=msg\n",
    "def validage(age):\n",
    "    if age<0:\n",
    "        raise validage (\"Entered age is not velid\")\n",
    "    elif age >200:\n",
    "        raise validage (\"entered age is more high\")\n",
    "    else:\n",
    "        print(\" age is valid\")\n",
    "try:\n",
    "    age =int (input(\"enter your age \"))\n",
    "    validage(age)\n",
    "except validage as e:\n",
    "    print (e)\n",
    "\n",
    "output//\n",
    "TypeError                                 Traceback (most recent call last)\n",
    "Cell In [15], line 3\n",
    "      2     age =int (input(\"enter your age \"))\n",
    "----> 3     validage(age)\n",
    "      4 except validage as e:\n",
    "\n",
    "Cell In [13], line 5, in validage(age)\n",
    "      4 elif age >200:\n",
    "----> 5     raise validage (\"entered age is more high\")\n",
    "      6 else:\n",
    "\n",
    "Cell In [13], line 2, in validage(age)\n",
    "      1 def validage(age):\n",
    "----> 2     if age<0:\n",
    "      3         raise validage (\"Entered age is not velid\")\n",
    "\n",
    "TypeError: '<' not supported between instances of 'str' and 'int'\n",
    "\n",
    "During handling of the above exception, another exception occurred:\n",
    "\n",
    "TypeError                                 Traceback (most recent call last)\n",
    "Cell In [15], line 4\n",
    "      2     age =int (input(\"enter your age \"))\n",
    "      3     validage(age)\n",
    "----> 4 except validage as e:\n",
    "      5     print (e)\n",
    "\n",
    "TypeError: catching classes that do not inherit from BaseException is not allowed\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
